daysUntilStale: 20
daysUntilClose: 7
exemptLabels:
  - pinned
  - security
  - WIP
  - Bug
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
unmarkComment: >
  This issue has been automatically marked as not stale because it has had recent activity.
closeComment: false
