/* tslint:disable */
/* eslint-disable */
/**
 * Events254
 * Events254 internal API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DefaultApi } from "./api";

declare module '#app' {
    interface NuxtApp {
        $events254Api: DefaultApi
    }
}




export default defineNuxtPlugin((nuxtApp) => {
    const { apiUrl, apiKey } = useRuntimeConfig().public
    let authToken: string
    if (process.client) {
        authToken = localStorage.getItem('auth.token')
    }
    class YouthAgentApi extends DefaultApi {
        constructor() {
            super();
            this.basePath = apiUrl
            this.axios.defaults.headers.common['x-api-key'] = apiKey,
                this.axios.defaults.headers.common['x-requested-with'] = 'mobile'
            this.axios.defaults.headers.common['Authorization'] = `Bearer ${authToken}`
        }
    }

    const api = new YouthAgentApi()
    nuxtApp.provide('events254Api', api)
})
