name: Build and Deploy to S3

on:
  push:
    branches:
      - main
jobs:
  build:
    environment:
            name: production
            url: https://events254.co.ke
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        API_URL: https://api.events254.co.ke
        APP_URL: https://events254.co.ke
        API_KEY: ${{ secrets.API_KEY }}
    runs-on: ubuntu-latest
    name: Build and Deploy to S3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
           node-version: '14'
      
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn generate
      - name: Upload to s3
        run: aws s3 sync dist/ s3://${secrets.AWS_BUCKET}/ --acl public-read --cache-control max-age=31536000,public
      - name: Invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
      